services:
  envato-purchase-backu:
    image: ghcr.io/norfair00/envato-purchase-backup-docker:master
    container_name: envato-purchase-backu
    environment:
      CONCURRENCY: "1"
      CRON: "0 */12 * * *"
      TZ: "Europe/Paris"
      ENVATO_PERSONAL_TOKEN: "viAL6awzUkzlNM1iftUJZbBLevVNgcyK"
      CF_ACCOUNT_ID: "" #set your cf account id
      CF_API_KEY: ""
      CF_D1_ID: ""
      CF_D1_TABLE: "purchases"
      R2_ENDPOINT: "https://$ACCOUNT_ID$.eu.r2.cloudflarestorage.com" #Change $ACCOUNT_ID$ with your cf account id
      R2_ACCESS_KEY: ""
      R2_SECRET_KEY: ""
      R2_BUCKET: "envato-purchase"